FROM php:8.0-fpm-bullseye
SHELL ["/bin/bash", "-oeux", "pipefail", "-c"]

# timezone
ENV TZ=Asia/Tokyo

# language
ENV LANG=ja_JP.UTF-8 \
  LANGUAGE=ja_JP:ja \
  LC_ALL=ja_JP.UTF-8

RUN apt-get update && \
  apt-get install -y locales && \
  apt-get clean && \
  locale-gen ja_JP.UTF-8 && \
  localedef -f UTF-8 -i ja_JP ja_JP.UTF-8

# composer
ENV COMPOSER_ALLOW_SUPERUSER=1 \
  COMPOSER_HOME=/composer

COPY --from=composer:2.1 /usr/bin/composer /usr/bin/composer

# package
RUN apt-get update && \
  apt-get -y install git libicu-dev libonig-dev libzip-dev unzip

# php
RUN docker-php-ext-install intl pdo_mysql zip bcmath

# copy
COPY ./docker/php/php-fpm.d/zzz-www.dev.conf /usr/local/etc/php-fpm.d/zzz-www.conf
COPY ./docker/php/etc/php.dev.ini /usr/local/etc/php/php.ini

# workdir
WORKDIR /work/app

