version: "3"

volumes:
  db-store:


services:
  web-app:
    build:
      context: .
      dockerfile: ./docker/php-apache/local/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
    networks:
      - net1

  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile.dev
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: template-project
      MYSQL_USER: template-project
      MYSQL_PASSWORD: template-project
      MYSQL_ROOT_PASSWORD: template-project
      TZ: 'Asia/Tokyo'
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
        volume:
          nocopy: true
    networks:
      - net1

  phpmyadmin:
    links:
      - db
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=template-project
      - PMA_PASSWORD=template-project
    ports:
      - "18080:80"
    networks:
      - net1

networks:
  net1:
